services:
  # KPI Service
  kpi-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trustroots-kpi-service
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./public:/app/public
    networks:
      - default
